// Generated by CoffeeScript 1.8.0
(function() {
  var bindings, interval, os;

  bindings = require('bindings')('avahi_pub.node');

  os = require('os');

  module.exports = {
    publish: function(opts) {
      var service;
      service = bindings.publish(opts);
      bindings.poll();
      return service;
    },
    isSupported: function() {
      return os.platform() === 'linux';
    },
    kill: function() {
      return clearInterval(interval);
    }
  };

  bindings.init();

  if (module.exports.isSupported()) {
    interval = setInterval(bindings.poll, 1000);
  }

}).call(this);
